typography_spectrum: 0.6454
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.46056847204454243
  lightness: 0.9632441764697433
  saturation: 0.3723311861976981
  rhythmicContrast: 0.3697203225456178
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.719008865300566
analytics:
  google: null
  facebook: null
  twitter: null
name: Michael James Reed
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Michael James Reed
description: Actor. Coach. Teacher.
purpose: []
