layout_spectrum: 0.30746725923381746
typography_spectrum: 0.6497801314108074
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.3478087766561657
  lightness: 0.8969909662846476
  saturation: 0.7877826052717865
  rhythmicContrast: 0.9339092073496431
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3e29274f-fb52-4443-95d7-6408f731ffa0.jpg
name: Michael James Reed
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Coaching
    id: d0bf36ec-d064-42d0-b6f8-c9d168bdbf56
    type: content
  - name: Headshots
    id: a0adfc13-9eb9-4749-8aa2-e0ff7236d414
    type: content
favicon: null
title: Michael James Reed
description: Actor. Coach. Teacher.
purpose: []
