layout_spectrum: 0.04254627297632396
typography_spectrum: 0.2163244914263487
color:
  saturation: 0.32824580115266144
  brandStrength: 0.3307658794801682
  lightness: 0.748334385221824
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  rhythmicContrast: 0.22544180555269122
title: Michael James Reed
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Actor. Coach. Teacher.
navigation:
  - name: Coaching
    id: d0bf36ec-d064-42d0-b6f8-c9d168bdbf56
    type: content
  - name: Headshots
    id: a0adfc13-9eb9-4749-8aa2-e0ff7236d414
    type: content
  - name: IMDB
    url: 'http://www.imdb.com/name/nm0715594/'
    type: external
cta:
  bucket: null
  version: null
  domain: null
name: Michael James Reed
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3e29274f-fb52-4443-95d7-6408f731ffa0.jpg
