layout_spectrum: 0.39464669954031706
typography_spectrum: 0.552083199378103
color:
  saturation: 0.450068281032145
  brandStrength: 0.0793727501295507
  lightness: 0.030039613135159016
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  rhythmicContrast: 0.5537031902931631
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3e29274f-fb52-4443-95d7-6408f731ffa0.jpg
name: Michael James Reed
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: IMDB
    url: 'http://www.imdb.com/name/nm0715594/'
    type: external
  - name: Coaching
    id: d0bf36ec-d064-42d0-b6f8-c9d168bdbf56
    type: content
  - name: Headshots
    id: a0adfc13-9eb9-4749-8aa2-e0ff7236d414
    type: content
  - name: Production Photos
    id: abadf086-55b1-4ebf-b0f2-fcf00d08bd52
    type: content
  - name: Video
    id: 5c55da68-677b-4bfb-b9c6-3b3407ef82da
    type: content
  - name: Voiceovers
    id: c4e06bf8-7e9d-4f25-9ea6-d348e88e95cc
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Michael James Reed
description: Actor. Coach. Teacher.
purpose: []
