title: Michael James Reed
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Actor. Coach. Teacher.
color:
  saturation: 0.3723311861976981
  brandStrength: 0.4605684720445424
  rhythmicContrast: 0.3697203225456178
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 0.9632441764697433
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Photos
    id: 3e46a602-b253-4bae-9eaf-75dc2116297c
    type: content
  - name: IMDB
    id: 9561163f-8bc5-4182-b3de-f57e4b55682b
    type: content
favicon: null
name: Michael James Reed
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6454
layout_spectrum: 0.5042553
