typography_spectrum: 0.6454
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.46056847204454243
  lightness: 0.9632441764697433
  saturation: 0.3723311861976981
  rhythmicContrast: 0.3697203225456178
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.719008865300566
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3e29274f-fb52-4443-95d7-6408f731ffa0.jpg
name: Michael James Reed
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Coaching
    id: d0bf36ec-d064-42d0-b6f8-c9d168bdbf56
    type: content
  - name: Headshots
    id: a0adfc13-9eb9-4749-8aa2-e0ff7236d414
    type: content
favicon: null
title: Michael James Reed
description: Actor. Coach. Teacher.
purpose: []
